version: "2"
services:
    nginx:
        build: ../netmessage_nginx
        ports:
            - "80:80"
        links:
             - "php-fpm"
#             - "redis"
        volumes:
            - "/var/www:/var/www:ro"
            - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    php-fpm:
        build: ../netmessage_php
        volumes:
            - "/var/www:/var/www:rw"
            #  - "./php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
#        links:
#            - "redis"
#   redis:
#        image: redis
#        ports:
#            - "6379:6379"